apiVersion: v1
kind: Namespace
metadata:
  name: flaresolverr

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flaresolverr-envs
  namespace: flaresolverr
data:
  FLARESOLVERR_GID: "100"
  FLARESOLVERR_UID: "1013"
  TZ: "Europe/Paris"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr-app
  namespace: flaresolverr
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/instance: flaresolverr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flaresolverr
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaresolverr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: flaresolverr-app
          image: ghcr.io/flaresolverr/flaresolverr:v3.3.7
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8191
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8191
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 8191
              hostPort: 8191
          envFrom:
            - configMapRef:
                name: flaresolverr-envs
          volumeMounts:
            - mountPath: /config
              name: config-volume
      volumes:
        - name: config-volume
          hostPath:
            # Ensure the file directory is created.
            path: /mnt/ssd/containers/config/flaresolverr
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-app
  namespace: flaresolverr
  labels:
    app.kubernetes.io/name: flaresolverr
spec:
  type: ClusterIP
  ports:
    - name: flaresolverr
      port: 8191
      protocol: TCP
      targetPort: 8191
  selector:
    app.kubernetes.io/name: flaresolverr

---
apiVersion: v1
kind: Endpoints
metadata:
  name: flaresolverr-app
  namespace: flaresolverr
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/instance: flaresolverr
subsets:
  - addresses:
      - ip: 192.168.1.116
    ports:
      - name: flaresolverr
        port: 8191
